name: Deploy to AWS

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
    # 1. Checkout the repository
    - name: Checkout code
      uses: actions/checkout@v3

    # 2. Set up Docker
    - name: Set up Docker
      uses: docker/setup-buildx-action@v2

    # 3. Log in to AWS ECR
    - name: Log in to Amazon ECR
      id: login-ecr
      uses: aws-actions/amazon-ecr-login@v2

    # 4. Build and push Docker images
    - name: Build and push backend image
      run: |
        docker build -t 034362067373.dkr.ecr.eu-central-1.amazonaws.com/backend:latest -f Dockerfile.backend .
        docker push 034362067373.dkr.ecr.eu-central-1.amazonaws.com/backend:latest

    - name: Build and push frontend image
      run: |
        docker build -t 034362067373.dkr.ecr.eu-central-1.amazonaws.com/frontend:latest -f Dockerfile.frontend .
        docker push 034362067373.dkr.ecr.eu-central-1.amazonaws.com/frontend:latest

    # 5. SSH into the EC2 instance and deploy
    - name: Deploy to EC2
      uses: appleboy/ssh-action@v0.5.0
      with:
        host: ${{ secrets.AWS_EC2_HOST }}
        username: ${{ secrets.AWS_EC2_USER }}
        key: ${{ secrets.AWS_EC2_KEY }}
        script: |
          docker pull 034362067373.dkr.ecr.eu-central-1.amazonaws.com/backend:latest
          docker pull 034362067373.dkr.ecr.eu-central-1.amazonaws.com/frontend:latest
          docker-compose up -d
